Implemented files called general_consts.go to all modules that heavly relied on  the duplicated "CLientID : 1"
CosmWasm/wasmd pull request #254
Opened 2020-08-19 11:37 UTC by gustavohmsilva

Future duplicated values across the entire module can also be added to it as constants, centralizing therefore all those kind of values in one place.

2020-08-19 13:44 UTC, alpe commented
@gustavohmsilva thank you very much for your contribution and the time and effort you invested into this.
I have commented on #10 to understand the original intention of the task better.

2020-08-26 07:04 UTC, alpe requested changes
Thanks again for your patience. 🌻 
The original intention of the issue is still not clear to me but to move this PR forward I have added a couple of comments to make this code more Go idiomatic.

2020-08-26 07:22 UTC, gustavohmsilva commented on x/wasm/internal/types/general_consts.go
> +	CID = 1
Ok, got it.

2020-08-26 07:23 UTC, gustavohmsilva commented on lcd_test/wasm_test.go
> +const CID = 1
got it.
Thanks for the video reference, as I'm studying Go this is very valuable.

2020-09-04 11:20 UTC, alpe commented
@gustavohmsilva just wondering: do you plan to modify the PR according to code review comments or leave it as it is?

2020-09-06 08:15 UTC, gustavohmsilva commented
Hi @alpe. I'll will, in a few minutes. Sorry for the delay. Things have been chaotic here.

2020-10-06 06:24 UTC, alpe approved these changes

2020-10-06 06:36 UTC, ethanfrey commented
Sorry for the slow response, I have not been working on wasmd for a while.

Thank you for this submission and I am merging it in preparation for our 0.11 release

2020-10-06 06:36 UTC, merged